### ISSUE TITLE
Consider moving Plotlyhs to a submodule or individual repo

### ISSUE THREAD

**Issue by JonathanReeve** [diffusionkinetics/open#124]
I know there are a few advantages to monorepos, but there are a few sticking points, as well. For instance, I wanted to contribute to PlotlyHS, which had its own repo originally, but I'm not really interested in all the other repos in this collection. So I've made [my own fork](https://github.com/JonathanReeve/plotlyhs) which is only plotlyhs, so that way I can [use it in my other software](https://github.com/JonathanReeve/plotlyhs) without having to import a ton of unnecessary packages. 

There's also the fact that, if I wanted to point Stack or Nix to a GitHub repo containing a custom version of some package, this would be much more difficult when they're all hidden in one giant repo. 

I'd suggest moving Plotlyhs, at least, to its own repo. That way, I and other contributors could hack around on it, import it in our own projects, and contribute back to it, without having to worry about all the other libraries in this monorepo. This would be better for you, since you'd get more contributions, but also for the rest of us, since they'd be easier to work with.

**Comment by glutamate** [comment]
I am no longer developing this repository, [Saltcorn](https://github.com/saltcorn/saltcorn) is now my main open source project in addition to my day job.

Feel free to take anything from here and put into separate repositories. The DataHaskell crowd has already done this for the datasets package. I think plotlyhs and datasets were the only two projects in this repository that found community traction.

Let me know if I need to do anything to help you take over this package on hackage, I'm also happy to push notices to this repository pointing users to new repositories.

**Comment by JonathanReeve** [comment]
Sounds great. I'll get in contact with the DataHaskell people about sharing the maintainence, but in the meantime I'd be happy to take it over myself. I've just created a Hackage account with the username JonathanReeve. (Same as my GitHub username.) If you'd want to transfer the ownership/maintainership to me, and post notes in the readmes here, and in [its original spot](https://github.com/glutamate/plotlyhs), that would get the ball rolling.

**Comment by JonathanReeve** [comment]
@glutamate, I'm all set to take over this package, if you want. I think I just need to be added as a maintainer in Hackage. My username is JonathanReeve.

**Comment by glutamate** [comment]
@JonathanReeve I think that should be done now, on hackage

**Comment by dschrempf** [comment]
Hi! May I ask about the status of this move? I could not find any new repository, nor does Jonathan appear to be a maintainer on Hackage. Thank you!

**Comment by JonathanReeve** [comment]
A couple years later than I should've, but I finally figured out all the Hackage stuff necessary, and changed the maintainer information, as well as published a new version with some of my latest changes. [Check it out here!](https://hackage.haskell.org/package/plotlyhs-0.2.2/candidate) Closing this issue as completed.

**Comment by dschrempf** [comment]
This is great, thank you!
