### ISSUE TITLE
Old Faithful data set should be the same as the one in R

### ISSUE THREAD

**Issue by idontgetoutmuch** [diffusionkinetics/open#26]
The R data set is different. I think most people (like me?) would think this *is* the R data set. I want to reproduce some results done in Python and it uses the R data set. Obviously I can create my own.

**Comment by glutamate** [comment]
Thanks for noticing this, indeed they should match because replicating algorithm results is a major goal. Does this match the dataset in R?

**Comment by glutamate** [comment]
https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/faithful.csv

**Comment by idontgetoutmuch** [comment]
👍
