### ISSUE TITLE
Contributing to diffusionkinetics/open

### ISSUE THREAD

**Issue by stites** [diffusionkinetics/open#48]
I was going to use this repo for some toy problems, but I'm wondering if #46 is a huge refactor that I should wait for -- does #46 make backward-incompatible changes to the API?

On a related note, if someone wants to contribute to this repository, how do development cycles and issue management work and how do end users become more aware of upcoming changes?

**Comment by glutamate** [comment]
#46 is something weird someone opened. the underlying changes are only to an added module to lucid-extras.

**Comment by glutamate** [comment]
there is currently zero project management on this repo!

**Comment by stites** [comment]
Haha, good to know. If I was looking to contribute, are there any places you would suggest looking at?

**Comment by glutamate** [comment]
@stites i will try to put up a roadmap, but a good place to start is #31 which will also make @NickSeagull happy

**Comment by stites** [comment]
Cool beans! I'll look into it

**Comment by NickSeagull** [comment]
Thinking about this all day (no jokes): Would you be open to "donating" these packages in separate repositories to dataHaskell? I think it would be useful to have them separatedly, so each of them has issues as a roadmap, and contributors could see easily what to fix.

If you dont like this, maybe making another Github organization called DiffusionKineticsOpen. I think that fragmentation of this environment you've created is important as it will attract more users, in my opinion.

Also, if you added it to the dataHaskell organization it would get even more visibility. But it's your word the one that matters 😄 

About the PR @stites , I havent had the time to work on it yet, but would like to.

**Comment by glutamate** [comment]
@NickSeagull experience has just shown that developing in a monorepo is smoother for development when there are interdependencies. E.g. both Facebook and Google each have *all* of their code in a single git repo; in haskell, look e.g. at the [yesod repo](https://github.com/yesodweb/yesod) to see this working. Every large project I have worked on in the past has started as several repos and we have ended up merging them into one repo and it has been a huge win.

**Comment by NickSeagull** [comment]
Sounds great! It's a matter of designing a well drawn roadmap then. Maybe you could add labels for the issues for each project?

**Comment by glutamate** [comment]
Here is the first one: https://github.com/diffusionkinetics/open/wiki/Inliterate-roadmap

**Comment by stites** [comment]
Thanks, @glutamate! Since you are already using Github for issue management, you might want to consider converting the roadmaps to Issues and Milestones (which is just a little less overhead to maintain). I'm not about to argue that Github is good for any kind of project management, though, so take my words with a grain of salt.
