### ISSUE TITLE
plotlyhs: more flexible symbols for markers

### ISSUE THREAD

**Issue by adamgundry** [diffusionkinetics/open#63]
Could the `_symbol` field of `Marker` use `ListOrElem Symbol`? I'd like to have different symbols for different markers in a single trace, and this is supported by `plotly.js`.

Also, I'd like to be able to use other symbols besides those enumerated in the `Symbol` type. I'm not sure of the best way to achieve this, however. We could:
 * Extend the `Symbol` enumeration with many more constructors for all the different shape variants supported by `plotly.js` (e.g. `Circle | CircleOpen | CircleDot | CircleOpenDot`).
 * Use a more complex type to capture the structure of `Symbols` (e.g. `Circle Openness Dottedness`).
 * Add a constructor which takes the name of a custom symbol (e.g. `CustomSymbol Text`).
 * Use `Value` instead of `Symbol` in the `_symbol` field type.

Any preferences? I'm happy to draft a PR for this but I'd appreciate feedback on how to proceed.

For reference, the docs for this field are here: https://plot.ly/javascript/reference/#scatter-marker-symbol

**Comment by glutamate** [comment]
@adamgundry done. i went for CustomSymbol which seems the least destructive escape hatch. you option 2 can still be done later, it sounds great.

**Comment by glutamate** [comment]
thanks
