### ISSUE TITLE
Can't build dashdo-examples

### ISSUE THREAD

**Issue by jhrcek** [diffusionkinetics/open#64]
When building dashdo examples like this:
```
cd dashdo-examples
stack build
```
I'm getting this error:
```
   /home/jhrcek/Devel/github.com/diffusionkinetics/open/dashdo-examples/lib/Dashdo/Examples/IrisKMeans.hs:53:53: error:
        Variable not in scope:
          kmeans :: Int -> Supervisor Identity () [VS.Vector Double] a0
```

Looking at recent commit history I see that kmeans function was removed in https://github.com/diffusionkinetics/open/commit/115af2d2f3446f588f1ff43081f6642756f2f0be

Could you please update the examples to be buildable again? I'd like to play with them..

**Comment by glutamate** [comment]
@jhrcek thanks, i know why that is.

**Comment by glutamate** [comment]
I have commented out the K means code until I get around to build a pure Haskell implementation.

**Comment by jhrcek** [comment]
Thank you :-)
