### ISSUE TITLE
Upload plotlyhs and lucid-extras to Stackage

### ISSUE THREAD

**Issue by NickSeagull** [diffusionkinetics/open#85]
Would it be possible to upload those two packages to Stackage?

I'm developing a tool that leverages `stack` and asks the user to install `inliterate`.
Without creating a `stack.yaml` for this purpose it is not possible.

It would be great if `plotly-hs` and `lucid-extras` were on Stackage, so one could just `stack install inliterate` :smile:

**Comment by glutamate** [comment]
https://github.com/fpco/stackage/pull/3656

**Comment by NickSeagull** [comment]
Thank you so much :pray:

**Comment by glutamate** [comment]
This is been merged in stackage. @NickSeagull do you know if I have to do anything to get it into LTS?

**Comment by NickSeagull** [comment]
Thanks @glutamate ! In theory, it should be described [in this section of their docs](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package-to-an-lts-snapshot)

But a summary would be:

* Check that your package can be built with that LTS major version (e.g. `stack build --test --bench --haddock --resolver lts-8.10`)
* Open up a new issue on the lts-haskell repo
        Specify the LTS major versions you would like your packages to go into (e.g. lts-8)
        Provide a list of packages you would like added
            If relevant, mention any upper bounds that are needed on those packages
* Be patient! The LTS releases are less frequent than Nightly. The Stackage curators will try to get to your issue as soon as possible, but it may take some time.
* We gradually stop maintainng old LTS major versions, so your request may take longer or be declined if it's for an old LTS.

**(Copy pasted from the documentation)**

**Comment by glutamate** [comment]
It sounds like it makes it into the head LTS automatically without doing anything else.
